services:
  - type: web
    name: DebitCopybook-Backend-Global
    env: java
    plan: free
    buildCommand: "./gradlew build -x test"

    # Adı sadələşdirdiyimiz üçün startCommand-ı da yeniləyirik
    startCommand: "java -jar build/libs/app.jar"

    healthCheckPath: /public/ping
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=75.0